### PR TITLE
Optimise get_sides() in standard pipeline

### PR DESCRIPTION
**Pull request by LucHayward**
In pipeline_modules.standard.get_sides() an unreasonable amount of time is spent doing presence checks over large lists. By converting this to a set first we can improve runtimes by a factor of 100-1000x.

On my machine this takes the runtime for get_sides() from 10 minutes to 2 seconds.

### CODE REVIEW

**Comment by freerafiki** [comment]
Hi! it is very clever! Thanks a lot! Let me test it shortly and I can merge the pull request (most likely by tomorrow)

**Comment by freerafiki** [comment]
Ok I tested it and it's super fast! I got the same results on the demo (plus a couple of Fantastic Breaks-based bad examples), I am not 100% sure why it is **_so_** fast with a set, but it's a simple huge speedup - thanks a lot @LucHayward !

**Comment by LucHayward** [comment]
Thanks @freerafiki, if you're curious its because doing a membership check on a list ```if a in b``` is an O(n) operation (we iterate over half the list on average) whereas on a set it is O(1) (we just doing a hash table lookup). Normally not an issue but when lists get very large and/or you do it thousands of times it adds up.

Thanks for a really nicely explained paper!

**Comment by freerafiki** [comment]
Now it makes a lot of sense. This is really helpful, because we were wondering how to improve that part. We did some experiments using dbscan for example (to get the segmentation quick without visiting all the nodes, it worked but it was also depending on the choice of the parameters), and this idea (that you implemented) does not change anything in the workflow while being actually much faster, so I really see no drawbacks. 
Thanks a lot for your help, I added an acknowledgement on the readme file! 

If you have any other comments or idea, they are welcome :wink:

**Comment by LucHayward** [comment]
Thanks for the ackowledgement!!

We also considered using DBScan and seem to be getting some good early results but if you ran into issues it's likely we will too. If we end up making good progress I will let you know.

**Pull request merged**
